org: theadriann
service: world-class-schedule-api
app: worldclass-schedule

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1


functions:
  scheduleAPI:
    handler: api/schedule.handler
    environment:
      EMAIL: ${param:LOGIN_EMAIL}
      PASSW: ${param:LOGIN_PASSW}
    events:
      - http:
          path: /index
          method: get
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

# - http: ANY /
# - http: 'ANY {proxy+}'